export { HomePage } from './Home'
export { DiscoverPage } from './Discover'
export { MatchesPage } from './Matches'
export { ProfilePage } from './Profile'
export { OnboardingPage } from './Onboarding'
export { WingmanPage } from './Wingman'
